version: '3.1'

services:

  db:
    image: mysql:8
    command: ['--default-authentication-plugin=mysql_native_password', '--skip-ssl']
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fifa19
      MYSQL_USER: fifa19
      MYSQL_PASSWORD: fifa19

# Create a dump
# docker exec some-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql