Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "developer"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", \
    inline: "which -s python || (export DEBIAN_FRONTEND=noninteractive && sudo apt-get -qy install python)"

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "developer_machine.yml"
  end
end
